// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-transactions.ts
import { createClient } from "npm:@supabase/supabase-js@^2.76.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_transactions_default = defineTool({
  name: "list_transactions",
  title: "List transactions",
  description: "List the signed-in user's finance transactions, most recent first. Optionally filter by type (income/expense) or category, and cap the number of rows returned.",
  inputSchema: {
    limit: z.number().int().min(1).max(200).default(50).describe("Maximum rows to return (1-200)."),
    type: z.enum(["income", "expense"]).optional().describe("Filter by transaction type."),
    category: z.string().optional().describe("Filter by exact category name.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, type, category }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = supabaseForUser(ctx).from("transactions").select("id,amount,type,category,description,date,currency,created_at").eq("user_id", ctx.getUserId()).order("date", { ascending: false }).limit(limit);
    if (type) q = q.eq("type", type);
    if (category) q = q.eq("category", category);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { transactions: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-transaction.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.76.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var create_transaction_default = defineTool2({
  name: "create_transaction",
  title: "Create transaction",
  description: "Record a new income or expense for the signed-in user. Amount must be positive; type is 'income' or 'expense'.",
  inputSchema: {
    amount: z2.number().positive().describe("Absolute amount, positive number."),
    type: z2.enum(["income", "expense"]).describe("Transaction type."),
    category: z2.string().trim().min(1).describe("Category name (e.g. 'Food', 'Salary')."),
    description: z2.string().trim().max(500).optional().describe("Optional free-text note."),
    date: z2.string().regex(/^\d{4}-\d{2}-\d{2}/).optional().describe("ISO date (YYYY-MM-DD). Defaults to today."),
    currency: z2.string().length(3).optional().describe("ISO currency code (default RON).")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ amount, type, category, description, date, currency }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser2(ctx).from("transactions").insert({
      user_id: ctx.getUserId(),
      amount,
      type,
      category,
      description: description ?? null,
      date: date ?? (/* @__PURE__ */ new Date()).toISOString().slice(0, 10),
      currency: currency ?? "RON"
    }).select().single();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: `Created transaction ${data.id}` }],
      structuredContent: { transaction: data }
    };
  }
});

// src/lib/mcp/tools/get-summary.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.76.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
function supabaseForUser3(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_summary_default = defineTool3({
  name: "get_finance_summary",
  title: "Get finance summary",
  description: "Return the signed-in user's total income, total expense, net balance, and per-category expense breakdown for a given month (defaults to the current month).",
  inputSchema: {
    year: z3.number().int().min(2e3).max(2100).optional().describe("Year (defaults to current year)."),
    month: z3.number().int().min(1).max(12).optional().describe("Month 1-12 (defaults to current month).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ year, month }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const now = /* @__PURE__ */ new Date();
    const y = year ?? now.getUTCFullYear();
    const m = month ?? now.getUTCMonth() + 1;
    const start = `${y}-${String(m).padStart(2, "0")}-01`;
    const endDate = new Date(Date.UTC(y, m, 1));
    const end = endDate.toISOString().slice(0, 10);
    const { data, error } = await supabaseForUser3(ctx).from("transactions").select("amount,type,category").eq("user_id", ctx.getUserId()).gte("date", start).lt("date", end);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    let income = 0;
    let expense = 0;
    const byCategory = {};
    for (const t of data ?? []) {
      const amt = Number(t.amount) || 0;
      if (t.type === "income") income += amt;
      else {
        expense += amt;
        byCategory[t.category] = (byCategory[t.category] ?? 0) + amt;
      }
    }
    const summary = {
      period: { year: y, month: m },
      income,
      expense,
      net: income - expense,
      expensesByCategory: byCategory,
      transactionCount: data?.length ?? 0
    };
    return {
      content: [{ type: "text", text: JSON.stringify(summary) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "rvqnnxbtxyybtzqnwmbe";
var mcp_default = defineMcp({
  name: "moneytracker-mcp",
  title: "MoneyTracker MCP",
  version: "0.1.0",
  instructions: "Tools for MoneyTracker, a personal finance tracker. Use `list_transactions` to read the signed-in user's income and expenses, `create_transaction` to record a new one, and `get_finance_summary` for monthly totals and category breakdowns.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_transactions_default, create_transaction_default, get_summary_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
